import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+919454929255", 
					"hey 1 this side Nidhi!....Automatic message generated by python code", 
					12, 46)
 
